services:
  k8s-cron:
    build:
      context: api
      dockerfile: cron.Dockerfile
    container_name: k8s-cron
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
