services:
  view:
    # image: node:20-alpine
    build:
      context: view
      target: prod
    container_name: view
    working_dir: /app
    volumes:
      - ./view:/app
      - ./view/.pnpm-store:/app/.pnpm-store
      - ./view/.next:/app/.next
      - ./openapi.yaml:/app/openapi.yaml
    ports:
      - 3000:3000
    env_file:
      ./view/prod.env
    # command: pnpm start

  api:
    build:
      context: api
      target: service
    container_name: api
    volumes:
      - ./api/src:/root/app
      - ./secret:/root/secret
    ports:
      - 8000:8000
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8000
    env_file:
      ./api/prod.env

  celery:
    build:
      context: api
      target: service
    container_name: celery
    volumes:
      - ./api/src:/root/app
      - ./secret:/root/secret
    command: celery -A celery_server.celery_app worker --loglevel=info
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
              driver: nvidia
    env_file:
      ./api/prod.env
    depends_on:
      - redis

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - 6379:6379

  cloudflare:
    image: "cloudflare/cloudflared:2025.2.1"
    container_name: "cloudflare"
    volumes: [ './cloudflare:/home/nonroot/.cloudflared' ]
    command: tunnel run
    restart: unless-stopped
