services:
  dev-view:
    build:
      context: view
      target: prod
    container_name: dev-view
    working_dir: /app
    command: yarn start
    ports:
      - 5000:3000

  prod-api:
    build:
      context: api
      target: service
    container_name: prod-api
    volumes:
      - ./api/src:/root/app
      - ./secret:/root/secret
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8000

  prod-celery:
    build:
      context: api
      target: service
    container_name: prod-celery
    volumes:
      - ./api/src:/root/app
      - ./secret:/root/secret
    command: celery -A celery_server.celery_app worker --loglevel=info
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
              driver: nvidia
    depends_on:
      - prod-redis

  prod-redis:
    image: redis:7.4
    container_name: prod-redis

  dev-cloudflare:
    image: "cloudflare/cloudflared:2025.2.1"
    container_name: "dev-cloudflare"
    volumes: [ './cloudflare:/home/nonroot/.cloudflared' ]
    command: tunnel run
    restart: unless-stopped
    depends_on:
      - dev-view
