services:
  prod-view:
    # image: node:20-alpine
    build:
      context: view
      target: prod
    container_name: prod-view
    working_dir: /app
    volumes:
      - ./view:/app
      - ./view/.pnpm-store:/app/.pnpm-store
      - ./view/.next:/app/.next
      - ./openapi.yaml:/app/openapi.yaml
    ports:
      - 3001:3001
    env_file:
      ./view/prod.env
    # command: pnpm start

  prod-api:
    build:
      context: api
      target: service
    container_name: prod-api
    volumes:
      - ./api/src:/root/app
      - ./secret:/root/secret
    ports:
      - 8001:8001
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8001
    env_file:
      ./api/prod.env

  prod-celery:
    build:
      context: api
      target: service
    container_name: prod-celery
    volumes:
      - ./api/src:/root/app
      - ./secret:/root/secret
    command: celery -A celery_server.celery_app worker --loglevel=info
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
              driver: nvidia
    env_file:
      ./api/prod.env
    depends_on:
      - prod-redis

  prod-redis:
    image: redis:7.4
    container_name: prod-redis

  cloudflare:
    image: "cloudflare/cloudflared:2025.2.1"
    container_name: "cloudflare"
    volumes: [ './cloudflare:/home/nonroot/.cloudflared' ]
    command: tunnel run
    restart: unless-stopped
