services:
  prod-view:
    build:
      context: view
      target: prod
    container_name: prod-view
    volumes:
      - ./view:/app
    working_dir: /app
    command: yarn start
    env_file:
      ./view/prod.env

  prod-api:
    build:
      context: api
      target: service
    container_name: prod-api
    volumes:
      - ./api/src:/root/app
      - ./secret:/root/secret
    command: uvicorn openapi_server.main:app --host 0.0.0.0 --port 8000
    env_file:
      ./api/prod.env

  prod-celery:
    build:
      context: api
      target: service
    container_name: prod-celery
    volumes:
      - ./api/src:/root/app
      - ./secret:/root/secret
    command: celery -A celery_server.celery_app worker --loglevel=info
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
              driver: nvidia
    env_file:
      ./api/prod.env
    depends_on:
      - prod-redis

  prod-cron:
    build:
      context: api
      target: service
    container_name: prod-cron
    volumes:
      - ./api/src:/root/app
      - ./secret:/root/secret
    environment:
      - CRON_INTERVAL_MINUTE=60
    command: python cron_job/refresh_wav_url.py
    env_file:
      ./api/prod.env

  prod-redis:
    image: redis:7.4
    container_name: prod-redis

  prod-cloudflare:
    image: "cloudflare/cloudflared:2025.2.1"
    container_name: "prod-cloudflare"
    volumes: [ './cloudflare:/home/nonroot/.cloudflared' ]
    command: tunnel run
    restart: unless-stopped
