services:
  view:
    build:
      context: view
      target: dev
    container_name: view
    working_dir: /app
    volumes:
      - ./view:/app
      - ./openapi.yaml:/app/openapi.yaml
    ports:
      - 3000:3000
    command: yarn dev
    
  api:
    build:
      context: api
      target: service
    container_name: api
    volumes:
      - ./api/src:/root/app
      - ./secret:/root/secret
    ports:
      - 8000:8000
    command: uvicorn openapi_server.main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      ./api/dev.env

  celery:
    build:
      context: api
      target: service
    container_name: celery
    volumes:
      - ./api/src:/root/app
      - ./secret:/root/secret
    command: watchmedo auto-restart --pattern="*.py" --recursive -- celery -A celery_server.celery_app worker --loglevel=info
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
              count: all
              driver: nvidia
    env_file:
      ./api/dev.env
    depends_on:
      - redis

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - 6379:6379

