services:
  api:
    build:
      context: api
      target: dev
    container_name: api
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secret/zennaihackason-552e64c1d8d1.json
    env_file:
      ./api/.env
    depends_on:
      - redis

  # celery:
  #   build:
  #     context: api
  #   container_name: celery
  #   volumes:
  #     - ./api:/app
  #   working_dir: /app/celery
  #   command: celery -A celery_app worker --loglevel=info
  #   depends_on:
  #     - redis

  redis:
    image: redis:7.4
    container_name: redis
    ports:
      - 6379:6379
