openapi: 3.0.0
info:
  title: MuSP API
  version: "1.0.0"
  description: |
    MuSPは、YouTubeリンクから音源をダウンロードし、Demucsで音源とボーカルを分離するWebアプリです。
    本API仕様書は、ジョブの作成、状態確認、分離済み音源の取得を提供します。
servers:
  - url: http://localhost:8000
security:
  - ApiKeyAuth: []

tags:
  - name: GET
    description: 取得関係
  - name: POST
    description: 作成関係
paths:
  /jobs:
    post:
      tags:
        - POST
      summary: 新規ジョブの作成
      description: YouTubeリンクを元に音源のダウンロードと音源/ボーカル分離のジョブを作成します。
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostJobsRequest"
      responses:
        "201":
          description: ジョブが正常に作成されました
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostJobsResponse"
        "400":
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /video_id/{user_id}:
    get:
      tags:
        - GET
      summary: ユーザーのYouTubeID一覧取得
      description: ユーザーが作成したYouTubeIDの一覧を取得します。
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/UserID"
      responses:
        "200":
          description: ユーザーのYouTubeID一覧を取得しました
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetVideoIDResponse"
        "400":
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /wav/{video_id}:
    get:
      tags:
        - GET
      summary: 分離済み音源の取得
      description: 分離済み音源のダウンロードリンクを取得します。
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/VideoID"
      responses:
        "200":
          description: 分離済み音源のダウンロードリンクを取得しました
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetWavResponse"
        "400":
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /users:
    post:
      tags:
        - POST
      summary: ユーザー情報の登録
      description: ユーザー情報を登録します。
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostUserRequest"
      responses:
        "200":
          description: ユーザーが存在します
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostUserResponse"
        "201":
          description: ユーザー情報が正常に登録されました
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostUserResponse"
        "400":
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  parameters:
    UserID:
      name: user_id
      in: path
      description: ユーザーID
      required: true
      schema:
        type: string
        maximum: 100
      example: testUser
    VideoID:
      name: video_id
      in: path
      description: YouTubeの動画ID
      required: true
      schema:
        type: string
        pattern: ^[a-zA-Z0-9_-]{11}$
        maximum: 11
      example: 57Q4Hp46oXc
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    PostJobsRequest:
      type: object
      example:
        user_id: "testUser"
        youtube_url: "https://www.youtube.com/watch?v=57Q4Hp46oXc"
      properties:
        user_id:
          type: string
          description: ユーザーID
          maximum: 100
        youtube_url:
          type: string
          description: YouTubeの動画リンク
          pattern: /^(?:https?://)?(?:www\.)?(?:youtube\.com/(?:watch\?.*v=|embed/|v/)|youtu\.be/)([a-zA-Z0-9_-]{11})/
          maximum: 100
      required:
        - user_id
        - youtube_url
      additionalProperties: false
    PostJobsResponse:
      type: object
      example:
        youtube_id: "57Q4Hp46oXc"
        message: "Job Created!"
      properties:
        youtube_id:
          type: string
          description: YouTubeの動画ID
          pattern: ^[a-zA-Z0-9_-]{11}$
          maximum: 11
      required:
        - youtube_id
      additionalProperties: false
    GetVideoIDResponse:
      type: object
      example:
        youtube_ids:
          - "57Q4Hp46oXc"
          - "57Q4Hp46oXd"
          - "57Q4Hp46oXe"
      properties:
        youtube_ids:
          type: array
          items:
            type: string
            description: YouTubeの動画ID
            pattern: ^[a-zA-Z0-9_-]{11}$
            maximum: 11
      additionalProperties: false
    GetWavResponse:
      type: object
      example:
        wav_url: "https://example.com/wav.wav"
      properties:
        wav_url:
          type: string
          format: uri
          description: 分離済み音源のURL
          maximum: 200
      required:
        - wav_url
      additionalProperties: false
    PostUserRequest:
      type: object
      example:
        google_id: "testGoogleID"
        nickname: "testNickname"
        icon_url: "https://example.com/icon.jpg"
      properties:
        google_id:
          type: string
          description: GoogleのユーザーID
          maximum: 100
        nickname:
          type: string
          description: ニックネーム
          maximum: 100
        icon_url:
          type: string
          format: uri
          description: アイコン画像のURL
          maximum: 200
      required:
        - google_id
        - nickname
        - icon_url
      additionalProperties: false
    PostUserResponse:
      type: object
      properties:
        user_id:
          type: string
          description: ユーザーID
          maximum: 100
      required:
        - user_id
      additionalProperties: false
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: エラーメッセージ
          maximum: 500
      required:
        - error
      additionalProperties: false
