openapi: 3.0.0
info:
  title: MuSP API
  version: "1.0.0"
  description: |
    MuSPは、YouTubeリンクから音源をダウンロードし、Demucsで音源とボーカルを分離するWebアプリです。
    本API仕様書は、ジョブの作成、状態確認、分離済み音源の取得を提供します。
servers:
  - url: http://localhost:8000
security:
  - ApiKeyAuth: []

tags:
  - name: CreateJob
    description: ジョブの作成
  - name: CheckJob
    description: ジョブの状態確認
  - name: GetURL
    description: オブジェクトストレージからURLを取得
paths:
  /jobs:
    post:
      tags:
        - CreateJob
      summary: 新規ジョブの作成
      description: YouTubeリンクを元に音源のダウンロードと音源/ボーカル分離のジョブを作成します。
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostJobsRequest"
      responses:
        "201":
          description: ジョブが正常に作成されました
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostJobsResponse"
        "400":
          description: 不正なリクエスト
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /jobs/{job_id}:
    get:
      tags: 
        - CheckJob
      summary: ジョブの状態確認
      description: 指定されたジョブIDの状態を取得します。
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/JobID"
      responses:
        "200":
          description: ジョブの状態情報
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetJobsResponse"
        "404":
          description: ジョブが見つかりませんでした
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /url/{job_id}:
    get:
      tags: 
        - GetURL
      summary: 分離された音源の取得
      description: 分離された音源のS3 URLを取得します。
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/JobID"
      responses:
        "200":
          description: 音源ファイルのS3 URLを返却
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetURLResponse"
        "404":
          description: 音源が見つかりませんでした
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /thumbnail/{job_id}:
    get:
      tags: 
        - GetURL
      summary: 分離された音源のサムネイル画像の取得
      description: 分離された音源のサムネイル画像のS3 URLを取得します。
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/JobID"
      responses:
        "200":
          description: サムネイル画像のS3 URLを返却
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetURLResponse"
        "404":
          description: サムネイル画像が見つかりませんでした
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
  /info/{user_id}:
    get:
      tags: 
        - GetURL
      summary: ギャラリー表示のための情報取得
      description: ギャラリー表示のための情報を取得します。
      security:
        - ApiKeyAuth: []
      parameters:
        - $ref: "#/components/parameters/UserID"
      responses:
        "200":
          description: ギャラリーを表示するために必要な情報を返却
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetInfoListResponse"
        "404":
          description: ジョブが見つかりませんでした
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /ws/jobs/{job_id}:
    get:
      tags: 
        - CheckJob
      summary: ジョブの進捗状況をWebSocketで取得
      description: WebSocketを使用して、ジョブの進捗状況をリアルタイムで取得します。
      parameters:
        - $ref: "#/components/parameters/JobID"
      responses:
        "101":
          description: WebSocket接続成功
        "404":
          description: ジョブが見つかりませんでした

components:
  parameters:
    JobID:
      name: job_id
      in: path
      description: ジョブの識別子
      required: true
      schema:
        type: string
        pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
        maximum: 36
    UserID:
      name: user_id
      in: path
      description: ユーザーID
      required: true
      schema:
        type: string
        maximum: 100
      example: testUser
  securitySchemes:
    ApiKeyAuth:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    PostJobsRequest:
      type: object
      example:
        user_id: "testUser"
        youtube_url: "https://www.youtube.com/watch?v=57Q4Hp46oXc"
      properties:
        user_id:
          type: string
          description: ユーザーID
          maximum: 100
        youtube_url:
          type: string
          format: uri
          description: YouTubeの動画リンク
          pattern: /^(?:https?://)?(?:www\.)?(?:youtube\.com/(?:watch\?.*v=|embed/|v/)|youtu\.be/)([a-zA-Z0-9_-]{11})/
          maximum: 100
      required:
        - user_id
        - youtube_url
      additionalProperties: false
    PostJobsResponse:
      type: object
      properties:
        job_id:
          type: string
          description: 作成されたジョブの識別子
          pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
          maximum: 36
        message:
          type: string
          description: 状況メッセージ
          maximum: 100
      required:
        - job_id
        - message
      additionalProperties: false
    GetJobsResponse:
      type: object
      properties:
        status:
          type: string
          description: ジョブの現在の状態
          enum:
            - PENDING
            - STARTED
            - SUCCESS
            - FAILURE
          maximum: 10
      required:
        - status
      additionalProperties: false
    GetURLResponse:
      type: object
      properties:
        job_id:
          type: string
          description: ジョブの識別子
          pattern: ^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$
          maximum: 36
        url:
          type: string
          format: uri
          description: 音源のS3 URL
      required:
        - job_id
        - url
      additionalProperties: false
    GetInfoResponse:
      type: object
      example:
        title: "testTitle"
        thumbnail_url: "https://i.ytimg.com/vi/57Q4Hp46oXc/hqdefault.jpg"
        wav_url: "https://musp-audio.s3.ap-northeast-1.amazonaws.com/57Q4Hp46oXc.wav"
      properties:
        title: 
          type: string
          description: タイトル
          maximum: 200
        thumbnail_url:
          type: string
          format: uri
          description: サムネイル画像のURL
          pattern: "^https?://i.ytimg.com/vi/([a-zA-Z0-9_-]{11})/(hqdefault|default|mqdefault|sddefault|maxresdefault).jpg$"
          maximum: 200
        wav_url:
          type: string
          format: uri
          description: 音源のURL
      required:
        - title
        - thumbnail_url
        - wav_url
      additionalProperties: false
    GetInfoListResponse:
      type: object
      properties:
        items:
          type: array
          description: ギャラリー表示のための情報のリスト
          items:
            $ref: "#/components/schemas/GetInfoResponse"
      required:
        - items
      additionalProperties: false
      example:
        items:
          - title: "testTitle"
            thumbnail_url: "https://i.ytimg.com/vi/57Q4Hp46oXc/hqdefault.jpg"
            wav_url: "https://musp-audio.s3.ap-northeast-1.amazonaws.com/57Q4Hp46oXc.wav"
          - title: "testTitle2"
            thumbnail_url: "https://i.ytimg.com/vi/57Q4Hp46oXc/hqdefault.jpg"
            wav_url: "https://musp-audio.s3.ap-northeast-1.amazonaws.com/57Q4Hp46oXc.wav"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: エラーメッセージ
          maximum: 500
      required:
        - error
      additionalProperties: false
