# coding: utf-8

"""
MuSP API

MuSP is a web application that downloads audio from YouTube links and separates the audio and vocals using Demucs. This API specification provides endpoints for job creation, status checking, and retrieving separated audio files.

The version of the OpenAPI document: 1.0.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

import os

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from openapi_server.apis.get_api import (
    router as GETApiRouter,
)
from openapi_server.apis.post_api import (
    router as POSTApiRouter,
)

origins = [
    os.getenv("FRONTEND_URL", "http://localhost:3000"),
]

app = FastAPI(
    title="MuSP API",
    description="MuSP is a web application that downloads audio from YouTube links and separates the audio and vocals using Demucs. This API specification provides endpoints for job creation, status checking, and retrieving separated audio files. ",
    version="1.0.0",
)

app.add_middleware(
    CORSMiddleware,  # type: ignore
    allow_origins=origins,  # 許可するオリジン
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(GETApiRouter)
app.include_router(POSTApiRouter)
