apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: musp
spec:
  project: default
  source:
    repoURL: 'https://github.com/AobaIwaki123/musp'
    targetRevision: deploy-on-gcp
    path: k8s/manifests
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: musp
  syncPolicy:
    automated:
      selfHeal: true
      prune: true