apiVersion: v1
kind: Secret
metadata:
  name: musp-secret
  namespace: musp
type: Opaque
stringData:
  # APIサーバーーとフロントエンドで共通のAPIキー。実際の値に置き換えてください。
  MUSP_API_KEY: "--- IGNORE ---" 
  # 動画を処理するCloud RunサービスのURL。実際のURLに置き換えてください。
  WORKER_LAUNCHER_URL: "http://musp-worker-launcher:8000"
  # フロントエンドで使用するFirebaseの環境変数。実際の値に置き換えてください。
  NEXT_PUBLIC_FIREBASE_APIKEY: "--- IGNORE ---" # Placeholder, update with actual API key for frontend if needed
  NEXT_PUBLIC_AUTHDOMAIN: "example.firebaseapp.com" # Firebase Auth domain for frontend
  NEXT_PUBLIC_STORAGEBUCKET: "example.appspot.com" # Firebase Storage bucket for frontend
  NEXT_PUBLIC_MESSAGINGSENDERID: "1234567890" # Firebase Messaging
  NEXT_PUBLIC_APPID: "--- IGNORE ---"  # Firebase App ID
  NEXT_PUBLIC_MEASUREMENTID: "G-XXXXXXXXXX" # Firebase Measurement ID for analytics