apiVersion: apps/v1
kind: Deployment
metadata:
  name: musp-api
  namespace: musp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: musp-api
  template:
    metadata:
      labels:
        app: musp-api
    spec:
      imagePullSecrets:
        - name: gcr-pull-secret
      containers:
        - name: musp-api
          image: gcr.io/my-docker-471807/musp-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: MUSP_API_KEY
              valueFrom:
                secretKeyRef:
                  name: musp-secret
                  key: MUSP_API_KEY
            - name: GOOGLE_CLOUD_PROJECT
              valueFrom:
                configMapKeyRef:
                  name: musp-config
                  key: GOOGLE_CLOUD_PROJECT
            - name: DATASET_ID
              value: "musp_v3"
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/root/secret/key.json"
            - name: FRONTEND_URL
              value: "http://musp.aooba.net"
            - name: BUCKET_NAME
              value: "musp-bucket"
          volumeMounts:
            - name: google-cloud-key
              mountPath: /root/secret
              readOnly: true
      volumes:
        - name: google-cloud-key
          secret:
            secretName: musp-secret