apiVersion: v1
kind: ConfigMap
metadata:
  name: musp-config
  namespace: musp
data:
  # Add shared environment variables here if necessary
  PROJECT_ID: "my-docker-471807" # Placeholder, update actual Project ID
