# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-03-03T06:39:39+00:00

from __future__ import annotations

from enum import Enum
from typing import Optional

from pydantic import AnyUrl, AwareDatetime, BaseModel, Field


class Status(Enum):
    pending = 'pending'
    processing = 'processing'
    completed = 'completed'
    failed = 'failed'


class Job(BaseModel):
    job_id: Optional[str] = Field(None, description='ジョブの識別子')
    status: Optional[Status] = Field(None, description='ジョブの現在の状態')
    youtube_url: Optional[str] = Field(None, description='入力されたYouTubeリンク')
    created_at: Optional[AwareDatetime] = Field(None, description='ジョブ作成日時')
    updated_at: Optional[AwareDatetime] = Field(None, description='ジョブ更新日時')


class JobsPostRequest(BaseModel):
    youtube_url: AnyUrl = Field(..., description='YouTubeの動画リンク')


class JobsPostResponse(BaseModel):
    job_id: Optional[str] = Field(None, description='作成されたジョブの識別子')
    message: Optional[str] = Field(None, description='状況メッセージ')


class Track(Enum):
    vocal = 'vocal'
    instrumental = 'instrumental'
