# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-03-03T06:39:39+00:00

from __future__ import annotations

from typing import Optional

from fastapi import FastAPI, Path
from models.generated_model import Job, JobsPostRequest, JobsPostResponse, Track

app = FastAPI(
    title="MuSP API",
    version="1.0.0",
    description="MuSPは、YouTubeリンクから音源をダウンロードし、Demucsで音源とボーカルを分離するWebアプリです。\n本API仕様書は、ジョブの作成、状態確認、分離済み音源の取得を提供します。\n",
    servers=[{"url": "http://localhost:8000"}],
)


@app.post("/jobs", response_model=None, responses={"201": {"model": JobsPostResponse}})
def post_jobs(body: JobsPostRequest) -> Optional[JobsPostResponse]:
    """
    新規ジョブの作成
    """
    pass


@app.get("/jobs/{jobId}", response_model=Job)
def get_jobs_job_id(job_id: str = Path(..., alias="jobId")) -> Job:
    """
    ジョブの状態確認
    """
    pass


@app.get("/jobs/{jobId}/{track}", response_model=bytes)
def get_jobs_job_id_track(
    job_id: str = Path(..., alias="jobId"), track: Track = ...
) -> bytes:
    """
    分離された音源の取得
    """
    pass
