openapi: 3.0.0
info:
  description: |
    MuSPは、YouTubeリンクから音源をダウンロードし、Demucsで音源とボーカルを分離するWebアプリです。
    本API仕様書は、ジョブの作成、状態確認、分離済み音源の取得を提供します。
  title: MuSP API
  version: 1.0.0
servers:
- url: http://localhost:8000/api/v1
security:
- ApiKeyAuth: []
tags:
- description: ジョブの作成
  name: CreateJob
- description: ジョブの状態確認
  name: CheckJob
- description: オブジェクトストレージからURLを取得
  name: GetURL
paths:
  /jobs:
    post:
      description: YouTubeリンクを元に音源のダウンロードと音源/ボーカル分離のジョブを作成します。
      requestBody:
        content:
          application/json:
            example:
              youtube_url: https://www.youtube.com/watch?v=XXXXXXXXXXX
            schema:
              $ref: '#/components/schemas/_jobs_post_request'
        required: true
      responses:
        "201":
          content:
            application/json:
              example:
                job_id: 18b80b91-c46a-4e04-9cb1-9a30b39f0a47
                message: Job created successfully
              schema:
                $ref: '#/components/schemas/_jobs_post_201_response'
          description: ジョブが正常に作成されました
        "400":
          content:
            application/json:
              example:
                error: Invalid request
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 不正なリクエスト
      security:
      - ApiKeyAuth: []
      summary: 新規ジョブの作成
      tags:
      - CreateJob
  /jobs/{job_id}:
    get:
      description: 指定されたジョブIDの状態を取得します。
      parameters:
      - description: ジョブの識別子
        explode: false
        in: path
        name: job_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                status: processing
              schema:
                $ref: '#/components/schemas/_jobs__job_id__get_200_response'
          description: ジョブの状態情報
        "404":
          content:
            application/json:
              example:
                error: Job not found
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: ジョブが見つかりませんでした
      security:
      - ApiKeyAuth: []
      summary: ジョブの状態確認
      tags:
      - CheckJob
  /url/{job_id}:
    get:
      description: 分離された音源のS3 URLを取得します。
      parameters:
      - description: ジョブの識別子
        explode: false
        in: path
        name: job_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                job_id: 18b80b91-c46a-4e04-9cb1-9a30b39f0a47
                url: https://musp-s3-bucket.s3.ap-northeast-1.amazonaws.com/18b80b91-c46a-4e04-9cb1-9a30b39f0a47/source.wav
              schema:
                $ref: '#/components/schemas/_url__job_id__get_200_response'
          description: 音源ファイルのS3 URLを返却
        "404":
          content:
            application/json:
              example:
                error: Source not found
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 音源が見つかりませんでした
      security:
      - ApiKeyAuth: []
      summary: 分離された音源の取得
      tags:
      - GetURL
  /thumbnail/{job_id}:
    get:
      description: 分離された音源のサムネイル画像のS3 URLを取得します。
      parameters:
      - description: ジョブの識別子
        explode: false
        in: path
        name: job_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              example:
                job_id: 18b80b91-c46a-4e04-9cb1-9a30b39f0a47
                thumbnail: https://musp-s3-bucket.s3.ap-northeast-1.amazonaws.com/18b80b91-c46a-4e04-9cb1-9a30b39f0a47/thumbnail.jpg
              schema:
                $ref: '#/components/schemas/_thumbnail__job_id__get_200_response'
          description: サムネイル画像のS3 URLを返却
        "404":
          content:
            application/json:
              example:
                error: Thumbnail not found
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: サムネイル画像が見つかりませんでした
      security:
      - ApiKeyAuth: []
      summary: 分離された音源のサムネイル画像の取得
      tags:
      - GetURL
  /ws/jobs/{job_id}:
    get:
      description: WebSocketを使用して、ジョブの進捗状況をリアルタイムで取得します。
      parameters:
      - description: ジョブの識別子
        explode: false
        in: path
        name: job_id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "101":
          description: WebSocket接続成功
        "404":
          description: ジョブが見つかりませんでした
      summary: ジョブの進捗状況をWebSocketで取得
      tags:
      - CheckJob
components:
  schemas:
    ErrorResponse:
      example:
        error: error
      properties:
        error:
          description: エラーメッセージ
          title: error
          type: string
      title: ErrorResponse
      type: object
    _jobs_post_request:
      properties:
        youtube_url:
          description: YouTubeの動画リンク
          format: uri
          title: youtube_url
          type: string
      required:
      - youtube_url
      title: _jobs_post_request
      type: object
    _jobs_post_201_response:
      example:
        job_id: job_id
        message: message
      properties:
        job_id:
          description: 作成されたジョブの識別子
          title: job_id
          type: string
        message:
          description: 状況メッセージ
          title: message
          type: string
      required:
      - job_id
      - message
      title: _jobs_post_201_response
      type: object
    _jobs__job_id__get_200_response:
      example:
        status: status
      properties:
        status:
          description: ジョブの現在の状態
          title: status
          type: string
      required:
      - status
      title: _jobs__job_id__get_200_response
      type: object
    _url__job_id__get_200_response:
      example:
        job_id: job_id
        url: https://openapi-generator.tech
      properties:
        job_id:
          description: ジョブの識別子
          title: job_id
          type: string
        url:
          description: 音源のS3 URL
          format: uri
          title: url
          type: string
      required:
      - job_id
      - url
      title: _url__job_id__get_200_response
      type: object
    _thumbnail__job_id__get_200_response:
      example:
        thumbnail: https://openapi-generator.tech
        job_id: job_id
      properties:
        job_id:
          description: ジョブの識別子
          title: job_id
          type: string
        thumbnail:
          description: 音源のサムネイル画像の URL
          format: uri
          title: thumbnail
          type: string
      required:
      - job_id
      - thumbnail
      title: _thumbnail__job_id__get_200_response
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
