openapi: 3.0.0
info:
  description: |
    MuSPは、YouTubeリンクから音源をダウンロードし、Demucsで音源とボーカルを分離するWebアプリです。
    本API仕様書は、ジョブの作成、状態確認、分離済み音源の取得を提供します。
  title: MuSP API
  version: 1.0.0
servers:
- url: http://localhost:8000
security:
- ApiKeyAuth: []
tags:
- description: 取得関係
  name: GET
- description: 作成関係
  name: POST
paths:
  /jobs:
    post:
      description: YouTubeリンクを元に音源のダウンロードと音源/ボーカル分離のジョブを作成します。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostJobsRequest'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostJobsResponse'
          description: ジョブが正常に作成されました
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 不正なリクエスト
      security:
      - ApiKeyAuth: []
      summary: 新規ジョブの作成
      tags:
      - POST
  /video_id/{user_id}:
    get:
      description: ユーザーが作成したYouTubeIDの一覧を取得します。
      parameters:
      - description: ユーザーID
        example: testUser
        explode: false
        in: path
        name: user_id
        required: true
        schema:
          maximum: 100
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVideoIDResponse'
          description: ユーザーのYouTubeID一覧を取得しました
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 不正なリクエスト
      security:
      - ApiKeyAuth: []
      summary: ユーザーのYouTubeID一覧取得
      tags:
      - GET
  /wav/{video_id}:
    get:
      description: 分離済み音源のダウンロードリンクを取得します。
      parameters:
      - description: YouTubeの動画ID
        example: 57Q4Hp46oXc
        explode: false
        in: path
        name: video_id
        required: true
        schema:
          maximum: 11
          pattern: "^[a-zA-Z0-9_-]{11}$"
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetWavResponse'
          description: 分離済み音源のダウンロードリンクを取得しました
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 不正なリクエスト
      security:
      - ApiKeyAuth: []
      summary: 分離済み音源の取得
      tags:
      - GET
  /users:
    post:
      description: ユーザー情報を登録します。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUserRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostUserResponse'
          description: ユーザーが存在します
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostUserResponse'
          description: ユーザー情報が正常に登録されました
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: 不正なリクエスト
      security:
      - ApiKeyAuth: []
      summary: ユーザー情報の登録
      tags:
      - POST
components:
  parameters:
    UserID:
      description: ユーザーID
      example: testUser
      explode: false
      in: path
      name: user_id
      required: true
      schema:
        maximum: 100
        type: string
      style: simple
    VideoID:
      description: YouTubeの動画ID
      example: 57Q4Hp46oXc
      explode: false
      in: path
      name: video_id
      required: true
      schema:
        maximum: 11
        pattern: "^[a-zA-Z0-9_-]{11}$"
        type: string
      style: simple
  schemas:
    PostJobsRequest:
      additionalProperties: false
      example:
        user_id: testUser
        youtube_url: https://www.youtube.com/watch?v=57Q4Hp46oXc
      properties:
        user_id:
          description: ユーザーID
          maximum: 100
          type: string
        youtube_url:
          description: YouTubeの動画リンク
          maximum: 100
          pattern: "/^(?:https?://)?(?:www\\.)?(?:youtube\\.com/(?:watch\\?.*v=|embed/|v/)|youtu\\\
            .be/)([a-zA-Z0-9_-]{11})/"
          type: string
      required:
      - user_id
      - youtube_url
      title: PostJobsRequest
      type: object
    PostJobsResponse:
      additionalProperties: false
      example:
        youtube_id: 57Q4Hp46oXc
        message: Job Created!
      properties:
        youtube_id:
          description: YouTubeの動画ID
          maximum: 11
          pattern: "^[a-zA-Z0-9_-]{11}$"
          type: string
      required:
      - youtube_id
      title: PostJobsResponse
      type: object
    GetVideoIDResponse:
      additionalProperties: false
      example:
        youtube_ids:
        - 57Q4Hp46oXc
        - 57Q4Hp46oXd
        - 57Q4Hp46oXe
      properties:
        youtube_ids:
          items:
            description: YouTubeの動画ID
            maximum: 11
            pattern: "^[a-zA-Z0-9_-]{11}$"
            type: string
          type: array
      title: GetVideoIDResponse
      type: object
    GetWavResponse:
      additionalProperties: false
      example:
        wav_url: https://example.com/wav.wav
      properties:
        wav_url:
          description: 分離済み音源のURL
          format: uri
          maximum: 200
          type: string
      required:
      - wav_url
      title: GetWavResponse
      type: object
    PostUserRequest:
      additionalProperties: false
      example:
        google_id: testGoogleID
        nickname: testNickname
        icon_url: https://example.com/icon.jpg
      properties:
        google_id:
          description: GoogleのユーザーID
          maximum: 100
          type: string
        nickname:
          description: ニックネーム
          maximum: 100
          type: string
        icon_url:
          description: アイコン画像のURL
          format: uri
          maximum: 200
          type: string
      required:
      - google_id
      - icon_url
      - nickname
      title: PostUserRequest
      type: object
    PostUserResponse:
      additionalProperties: false
      example:
        user_id: user_id
      properties:
        user_id:
          description: ユーザーID
          maximum: 100
          title: user_id
          type: string
      required:
      - user_id
      title: PostUserResponse
      type: object
    ErrorResponse:
      additionalProperties: false
      example:
        error: error
      properties:
        error:
          description: エラーメッセージ
          maximum: 500
          title: error
          type: string
      required:
      - error
      title: ErrorResponse
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
