openapi: 3.0.0
info:
  description: |
    MuSPは、YouTubeリンクから音源をダウンロードし、Demucsで音源とボーカルを分離するWebアプリです。
    本API仕様書は、ジョブの作成、状態確認、分離済み音源の取得を提供します。
  title: MuSP API
  version: 1.0.0
servers:
- url: http://localhost:8000
security:
- ApiKeyAuth: []
tags:
- description: 取得関係
  name: GET
- description: 作成関係
  name: POST
paths:
  /video:
    post:
      description: YouTubeリンクを元に音源のダウンロードと音源/ボーカル分離のジョブを作成します。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostVideoRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostVideoResponse200'
          description: そのvideoは既に登録されています
        "202":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostVideoResponse202'
          description: ジョブが正常に作成されました
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
          description: 不正なリクエスト
      security:
      - ApiKeyAuth: []
      summary: 新規ジョブの作成
      tags:
      - POST
  /{user_id}:
    get:
      description: ユーザーが作成したYouTubeIDとWavURLの一覧を取得します。
      parameters:
      - description: ユーザーID
        example: testUser
        explode: false
        in: path
        name: user_id
        required: true
        schema:
          maximum: 100
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetVideoIDAndWavURLResponse200'
          description: ユーザーのYouTubeIDとWavURLの一覧を取得しました
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
          description: 不正なリクエスト
      security:
      - ApiKeyAuth: []
      summary: ユーザーのYouTubeIDとWavURLの一覧取得
      tags:
      - GET
  /users:
    post:
      description: ユーザー情報を登録します。
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PostUserRequest'
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostUserResponse200'
          description: ユーザーが存在します
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PostUserResponse201'
          description: ユーザー情報が正常に登録されました
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse400'
          description: 不正なリクエスト
      security:
      - ApiKeyAuth: []
      summary: ユーザー情報の登録
      tags:
      - POST
components:
  parameters:
    UserID:
      description: ユーザーID
      example: testUser
      explode: false
      in: path
      name: user_id
      required: true
      schema:
        maximum: 100
        type: string
      style: simple
  schemas:
    PostVideoRequest:
      additionalProperties: false
      example:
        user_id: testUser
        youtube_url: https://www.youtube.com/watch?v=57Q4Hp46oXc
      properties:
        user_id:
          description: ユーザーID
          maximum: 100
          type: string
        youtube_url:
          description: YouTubeの動画リンク
          maximum: 100
          pattern: "/^(?:https?://)?(?:www\\.)?(?:youtube\\.com/(?:watch\\?.*v=|embed/|v/)|youtu\\\
            .be/)([a-zA-Z0-9_-]{11})/"
          type: string
      required:
      - user_id
      - youtube_url
      title: PostVideoRequest
      type: object
    PostVideoResponse200:
      additionalProperties: false
      example:
        youtube_id: 57Q4Hp46oXc
        message: Video already exists!
      properties:
        youtube_id:
          description: YouTubeの動画ID
          maximum: 11
          pattern: "^[a-zA-Z0-9_-]{11}$"
          type: string
      required:
      - youtube_id
      title: PostVideoResponse200
      type: object
    PostVideoResponse202:
      additionalProperties: false
      example:
        youtube_id: 57Q4Hp46oXc
        message: Job Created!
      properties:
        youtube_id:
          description: YouTubeの動画ID
          maximum: 11
          pattern: "^[a-zA-Z0-9_-]{11}$"
          type: string
      required:
      - youtube_id
      title: PostVideoResponse202
      type: object
    VideoIDAndWavURL:
      additionalProperties: false
      properties:
        youtube_id:
          description: YouTubeの動画ID
          maximum: 11
          pattern: "^[a-zA-Z0-9_-]{11}$"
          title: youtube_id
          type: string
        wav_url:
          description: 分離済み音源のURL
          format: uri
          maximum: 200
          title: wav_url
          type: string
      required:
      - youtube_id
      title: VideoIDAndWavURL
      type: object
    GetVideoIDAndWavURLResponse200:
      additionalProperties: false
      example:
        data:
        - youtube_id: 57Q4Hp46oXc
          wav_url: https://example.com/wav.wav
        - youtube_id: 57Q4Hp46oXc
          wav_url: null
      properties:
        data:
          items:
            $ref: '#/components/schemas/VideoIDAndWavURL'
          type: array
      required:
      - data
      title: GetVideoIDAndWavURLResponse200
      type: object
    PostUserRequest:
      additionalProperties: false
      example:
        google_id: testGoogleID
      properties:
        google_id:
          description: GoogleのユーザーID
          maximum: 100
          type: string
      required:
      - google_id
      title: PostUserRequest
      type: object
    PostUserResponse200:
      additionalProperties: false
      example:
        user_id: user_id
      properties:
        user_id:
          description: ユーザーID
          maximum: 100
          title: user_id
          type: string
      required:
      - user_id
      title: PostUserResponse200
      type: object
    PostUserResponse201:
      additionalProperties: false
      example:
        user_id: user_id
      properties:
        user_id:
          description: ユーザーID
          maximum: 100
          title: user_id
          type: string
      required:
      - user_id
      title: PostUserResponse201
      type: object
    ErrorResponse400:
      additionalProperties: false
      example:
        error: error
      properties:
        error:
          description: エラーメッセージ
          maximum: 500
          title: error
          type: string
      required:
      - error
      title: ErrorResponse400
      type: object
  securitySchemes:
    ApiKeyAuth:
      in: header
      name: X-API-KEY
      type: apiKey
